urls:
  - 66, https://docs.fireworks.ai/api-reference/delete-dataset
  - 67, https://docs.fireworks.ai/api-reference/list-fine-tuning-jobs
  - 68, https://docs.fireworks.ai/api-reference/get-fine-tuning-job
  - 69, https://docs.fireworks.ai/api-reference/create-fine-tuning-job
  - 70, https://docs.fireworks.ai/api-reference/update-fine-tuning-job
  - 71, https://docs.fireworks.ai/api-reference/delete-fine-tuning-job
  - 72, https://docs.fireworks.ai/cookbook/cookbook_landing
  - 73, https://docs.fireworks.ai/cookbook/learn_with_fireworks/ecosystem_examples
  - 74, https://docs.fireworks.ai/cookbook/projects_showcase/community_examples
  - 75, https://docs.fireworks.ai/tools-sdks/firectl/firectl
  - 76, https://docs.fireworks.ai/tools-sdks/firectl/commands/authentication
  - 77, https://docs.fireworks.ai/tools-sdks/firectl/commands/list-models
  - 78, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-deployment
  - 79, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-finetune-job
  - 80, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-dataset
  - 81, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-model
  - 82, https://docs.fireworks.ai/tools-sdks/firectl/commands/delete-model
  - 83, https://docs.fireworks.ai/tools-sdks/firectl/commands/deploy-model
  - 84, https://docs.fireworks.ai/tools-sdks/firectl/commands/download-model
  - 85, https://docs.fireworks.ai/tools-sdks/firectl/commands/get-model
  - 86, https://docs.fireworks.ai/tools-sdks/firectl/commands/import-model
  - 87, https://docs.fireworks.ai/tools-sdks/firectl/commands/undeploy-model
  - 88, https://docs.fireworks.ai/tools-sdks/python-client/installation
  - 89, https://docs.fireworks.ai/tools-sdks/python-client/api-reference
  - 90, https://docs.fireworks.ai/tools-sdks/openai-compatibility
