urls:
  - https://docs.fireworks.ai/getting-started/introduction
  - https://docs.fireworks.ai/getting-started/quickstart
  - https://docs.fireworks.ai/getting-started/concepts
  - https://docs.fireworks.ai/guides/querying-text-models
  - https://docs.fireworks.ai/guides/querying-vision-language-models
  - https://docs.fireworks.ai/guides/querying-embeddings-models
  - https://docs.fireworks.ai/guides/function-calling
  - https://docs.fireworks.ai/structured-responses/structured-output-grammar-based
  - https://docs.fireworks.ai/structured-responses/structured-response-formatting
  - https://docs.fireworks.ai/guides/prompt-caching
  - https://docs.fireworks.ai/models/overview
  - https://docs.fireworks.ai/models/uploading-custom-models
  - https://docs.fireworks.ai/fine-tuning/fine-tuning-models
  - https://docs.fireworks.ai/fine-tuning/fine-tuning-via-api
  - https://docs.fireworks.ai/guides/lora-model-merge
  - https://docs.fireworks.ai/models/deploying
  - https://docs.fireworks.ai/models/quantization
  - https://docs.fireworks.ai/guides/ondemand-deployments
  - https://docs.fireworks.ai/deployments/regions
  - https://docs.fireworks.ai/deployments/reservations
  - https://docs.fireworks.ai/deployments/direct-routing
  - https://docs.fireworks.ai/guides/server-apps-quickstart
  - https://docs.fireworks.ai/guides/server-apps
  - https://docs.fireworks.ai/guides/quotas_usage/rate-limits
  - https://docs.fireworks.ai/accounts/users
  - https://docs.fireworks.ai/accounts/sso
  - https://docs.fireworks.ai/guides/security_compliance/data_handling
  - https://docs.fireworks.ai/troubleshooting/status_error_codes/inference_error_code
  - https://docs.fireworks.ai/troubleshooting/status_error_codes/inference_error_code
  - https://docs.fireworks.ai/api-reference/introduction
  - https://docs.fireworks.ai/api-reference/post-chatcompletions
  - https://docs.fireworks.ai/api-reference/post-completions
  - https://docs.fireworks.ai/api-reference/creates-an-embedding-vector-representing-the-input-text
  - https://docs.fireworks.ai/api-reference/generate-a-new-image-from-a-text-prompt
  - https://docs.fireworks.ai/api-reference/audio-transcriptions
  - https://docs.fireworks.ai/api-reference/audio-translations
  - https://docs.fireworks.ai/api-reference/audio-alignments
  - https://docs.fireworks.ai/api-reference/audio-realtime-transcriptions
  - https://docs.fireworks.ai/api-reference/get-account
  - https://docs.fireworks.ai/api-reference/list-deployments
  - https://docs.fireworks.ai/api-reference/get-deployment
  - https://docs.fireworks.ai/api-reference/create-deployment
  - https://docs.fireworks.ai/api-reference/update-deployment
  - https://docs.fireworks.ai/api-reference/delete-deployment
  - https://docs.fireworks.ai/api-reference/create-deployed-model
  - https://docs.fireworks.ai/api-reference/delete-deployed-model
  - https://docs.fireworks.ai/api-reference/list-models
  - https://docs.fireworks.ai/api-reference/get-model
  - https://docs.fireworks.ai/api-reference/create-model
  - https://docs.fireworks.ai/api-reference/update-model
  - https://docs.fireworks.ai/api-reference/delete-model
  - https://docs.fireworks.ai/api-reference/get-model-upload-endpoint
  - https://docs.fireworks.ai/api-reference/get-model-download-endpoint
  - https://docs.fireworks.ai/api-reference/validate-model-upload
  - https://docs.fireworks.ai/api-reference/list-users
  - https://docs.fireworks.ai/api-reference/get-user
  - https://docs.fireworks.ai/api-reference/create-user
  - https://docs.fireworks.ai/api-reference/update-user
  - https://docs.fireworks.ai/api-reference/list-datasets
  - https://docs.fireworks.ai/api-reference/get-dataset
  - https://docs.fireworks.ai/api-reference/create-dataset
  - https://docs.fireworks.ai/api-reference/upload-dataset-files
  - https://docs.fireworks.ai/api-reference/get-dataset-upload-endpoint
  - https://docs.fireworks.ai/api-reference/validate-dataset-upload
  - https://docs.fireworks.ai/api-reference/update-dataset
  - https://docs.fireworks.ai/api-reference/delete-dataset
  - https://docs.fireworks.ai/api-reference/list-fine-tuning-jobs
  - https://docs.fireworks.ai/api-reference/get-fine-tuning-job
  - https://docs.fireworks.ai/api-reference/create-fine-tuning-job
  - https://docs.fireworks.ai/api-reference/update-fine-tuning-job
  - https://docs.fireworks.ai/api-reference/delete-fine-tuning-job
  - https://docs.fireworks.ai/cookbook/cookbook_landing
  - https://docs.fireworks.ai/cookbook/learn_with_fireworks/ecosystem_examples
  - https://docs.fireworks.ai/cookbook/projects_showcase/community_examples
  - https://docs.fireworks.ai/tools-sdks/firectl/firectl
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/authentication
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/list-models
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/create-deployment
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/create-finetune-job
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/create-dataset
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/create-model
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/delete-model
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/deploy-model
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/download-model
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/get-model
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/import-model
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/undeploy-model
  - https://docs.fireworks.ai/tools-sdks/firectl/commands/update
  - https://docs.fireworks.ai/tools-sdks/python-client/installation
  - https://docs.fireworks.ai/tools-sdks/python-client/api-reference
  - https://docs.fireworks.ai/tools-sdks/openai-compatibility
